### ISSUE TITLE
Sharing is Caring.

### ISSUE THREAD

**Issue by iDump-ster** [ntsd/LoL-Auto-Clicker#1]
I've referred back to this page for usage of this, or its core for Pick a Card.
This is what I have for TF, and it seems to work very consistently.
Cheers!
```#SingleInstance force
#NoEnv
Menu, tray, Tip, TF CardPick
TrayTip, Pick a Fate, running...,,16
#IfWinActive League of Legends (TM) Client ahk_class RiotWindowClass
 
Global Spell_PAC := "w"
Global AutoAttack  := "a"
Global TimerLoop := "20" ; SECONDS
 
F5::Reload
 
$F1::Card("Gold")
$F2::Card("Red")
$F3::Card("Blue")
 
; | - - EDiT AT YOUR OWN RISK - - |
;|| \-/-\-/\-/-\-/\-/-\-/\-/-\-/\-/||
; | - - - - - - - - C O R E - - - - - - -   |
;|| /-\-/-\/-\-/-\/-\-/-\/-\-/-\/-\||
 
RandomSleep(Between1, Between2) {
	Random, RandomizedSleepTime, Between1, Between2
	Sleep, RandomizedSleepTime
}
 
CSpell() {
send, {%Spell_PAC% down} ;Pick a Card
RandomSleep(10,25)
send, {%Spell_PAC% up}
}
 
GAP(RatioX, RatioY) { ; GetAbsolutePixels
	WinGetPos,,, Width, Height
	AbsoluteX := Round(Width * RatioX)
	AbsoluteY := Round(Height * RatioY)
	return [AbsoluteX, AbsoluteY]
}
 
Card(color) {
	TopL := GAP(0.44, 0.91)
	BtmR := GAP(0.46, 0.95)
	TTsTaTus := GAP(0.47, 0.90)
	Tooltip, Looking for %color%, TTsTaTus[1], TTsTaTus[2]-15
	c := 0
	Cards:
	TTimer :=floor(c)
	Tooltip, Looking for %color% [%TTimer%/%TimerLoop%], TTsTaTus[1], TTsTaTus[2]-15
	c += .07 ;semi close to counting the loop per second.
		if c >= %TimerLoop%
		{
		Tooltip,
		Return
		}
	ImageSearch, %color%, , TopL[1], TopL[2], BtmR[1], BtmR[2], *120 %color%Card.png
	while %color% {
		CSpell()
		Send, {%AutoAttack%}
		Goto Cards
	}
	RandomSleep(15,25)
	Goto Cards
}

**Comment by ntsd** [comment]
> I've referred back to this page for usage of this, or its core for Pick a Card.
> This is what I have for TF, and it seems to work very consistently.
> Cheers!
> 
> ```
> #NoEnv
> Menu, tray, Tip, TF CardPick
> TrayTip, Pick a Fate, running...,,16
> #IfWinActive League of Legends (TM) Client ahk_class RiotWindowClass
>  
> Global Spell_PAC := "w"
> Global AutoAttack  := "a"
> Global TimerLoop := "20" ; SECONDS
>  
> F5::Reload
>  
> $F1::Card("Gold")
> $F2::Card("Red")
> $F3::Card("Blue")
>  
> ; | - - EDiT AT YOUR OWN RISK - - |
> ;|| \-/-\-/\-/-\-/\-/-\-/\-/-\-/\-/||
> ; | - - - - - - - - C O R E - - - - - - -   |
> ;|| /-\-/-\/-\-/-\/-\-/-\/-\-/-\/-\||
>  
> RandomSleep(Between1, Between2) {
> 	Random, RandomizedSleepTime, Between1, Between2
> 	Sleep, RandomizedSleepTime
> }
>  
> CSpell() {
> send, {%Spell_PAC% down} ;Pick a Card
> RandomSleep(10,25)
> send, {%Spell_PAC% up}
> }
>  
> GAP(RatioX, RatioY) { ; GetAbsolutePixels
> 	WinGetPos,,, Width, Height
> 	AbsoluteX := Round(Width * RatioX)
> 	AbsoluteY := Round(Height * RatioY)
> 	return [AbsoluteX, AbsoluteY]
> }
>  
> Card(color) {
> 	TopL := GAP(0.44, 0.91)
> 	BtmR := GAP(0.46, 0.95)
> 	TTsTaTus := GAP(0.47, 0.90)
> 	Tooltip, Looking for %color%, TTsTaTus[1], TTsTaTus[2]-15
> 	c := 0
> 	Cards:
> 	TTimer :=floor(c)
> 	Tooltip, Looking for %color% [%TTimer%/%TimerLoop%], TTsTaTus[1], TTsTaTus[2]-15
> 	c += .07 ;semi close to counting the loop per second.
> 		if c >= %TimerLoop%
> 		{
> 		Tooltip,
> 		Return
> 		}
> 	ImageSearch, %color%, , TopL[1], TopL[2], BtmR[1], BtmR[2], *120 %color%Card.png
> 	while %color% {
> 		CSpell()
> 		Send, {%AutoAttack%}
> 		Goto Cards
> 	}
> 	RandomSleep(15,25)
> 	Goto Cards
> }
> ```

Thank you. 
I'm so sorry that I haven't played this game anymore.
